package br.com.sideral.controller;
import java.io.IOException; import java.util.List; import javax.servlet.http.HttpServletResponse; import br.com.sideral.domain.ControlItem; import br.com.sideral.domain.Deployment; import br.com.sideral.service.ControlItemService; import br.com.sideral.service.DeploymentService; import com.lowagie.text.Document; import com.lowagie.text.Paragraph; import com.lowagie.text.pdf.PdfWriter; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Controller; import org.springframework.web.bind.annotation.PathVariable; import org.springframework.web.bind.annotation.RequestMapping; import org.springframework.web.bind.annotation.RequestMethod;
@Controller @RequestMapping("/relatorios")
public class ExportController {
 @Autowired private ControlItemService controlItems; @Autowired private DeploymentService deployments;
 @RequestMapping(value="/farol",method=RequestMethod.GET) public String traffic(){return "report/traffic";}
 @RequestMapping(value="/farol/excel",method=RequestMethod.GET) public void excel(HttpServletResponse response)throws IOException {response.setContentType("application/vnd.ms-excel");response.setHeader("Content-Disposition","attachment; filename=farol.xls");response.getWriter().println("Código\tItem\tÁrea\tMeta\tAtual\tFarol");for(ControlItem i:controlItems.list())response.getWriter().println(i.getCode()+"\t"+i.getName()+"\t"+i.getArea()+"\t"+i.getTarget()+"\t"+i.getCurrentValue()+"\t"+i.getTrafficColor());}
 @RequestMapping(value="/farol/word",method=RequestMethod.GET) public void word(HttpServletResponse response)throws IOException {response.setContentType("application/msword");response.setHeader("Content-Disposition","attachment; filename=relatorio-farol.doc");StringBuilder h=new StringBuilder("<html><head><meta charset='UTF-8'></head><body><h1>Relatório de Farol - Sideral</h1><table border='1'><tr><th>Código</th><th>Item</th><th>Farol</th></tr>");for(ControlItem i:controlItems.list())h.append("<tr><td>").append(i.getCode()).append("</td><td>").append(i.getName()).append("</td><td>").append(i.getTrafficColor()).append("</td></tr>");response.getWriter().print(h.append("</table></body></html>"));}
 @RequestMapping(value="/farol/pdf",method=RequestMethod.GET) public void pdf(HttpServletResponse response)throws Exception {response.setContentType("application/pdf");response.setHeader("Content-Disposition","attachment; filename=relatorio-farol.pdf");Document document=new Document();PdfWriter.getInstance(document,response.getOutputStream());document.open();document.add(new Paragraph("RELATÓRIO DE FAROL - SIDERAL GERENCIAL"));document.add(new Paragraph(""));for(ControlItem i:controlItems.list())document.add(new Paragraph(i.getCode()+" | "+i.getName()+" | "+i.getArea()+" | "+i.getTrafficColor()));document.close();}
 @RequestMapping(value="/farol/dados",method=RequestMethod.GET,produces="application/json") public @org.springframework.web.bind.annotation.ResponseBody List<ControlItem> data(){return controlItems.list();}
 @RequestMapping(value="/{kind}/{format}",method=RequestMethod.GET) public void operationalReport(@PathVariable String kind,@PathVariable String format,HttpServletResponse response)throws Exception {if(!"itens-controle".equals(kind)&&!"desdobramentos".equals(kind))throw new IllegalArgumentException("Relatório inválido");String title="itens-controle".equals(kind)?"RELATÓRIO DE ITENS DE CONTROLE":"RELATÓRIO DE DESDOBRAMENTOS";String content=buildContent(kind);if("excel".equals(format)){response.setContentType("application/vnd.ms-excel");response.setHeader("Content-Disposition","attachment; filename="+kind+".xls");response.getWriter().print(content.replace(" | ","\t"));return;}if("word".equals(format)){response.setContentType("application/msword");response.setHeader("Content-Disposition","attachment; filename="+kind+".doc");response.getWriter().print("<html><body><h1>"+title+"</h1><pre>"+content+"</pre></body></html>");return;}if("pdf".equals(format)){response.setContentType("application/pdf");response.setHeader("Content-Disposition","attachment; filename="+kind+".pdf");Document d=new Document();PdfWriter.getInstance(d,response.getOutputStream());d.open();d.add(new Paragraph(title));d.add(new Paragraph(""));for(String line:content.split("\\n"))d.add(new Paragraph(line));d.close();return;}response.sendError(HttpServletResponse.SC_NOT_FOUND,"Formato não suportado");}
 private String buildContent(String kind){StringBuilder text=new StringBuilder();if("itens-controle".equals(kind)){text.append("Código | Indicador | Área | Meta | Atual | Farol\n");for(ControlItem i:controlItems.list())text.append(i.getCode()).append(" | ").append(i.getName()).append(" | ").append(i.getArea()).append(" | ").append(i.getTarget()).append(" | ").append(i.getCurrentValue()).append(" | ").append(i.getTrafficColor()).append("\n");}else{text.append("Item | Ação | Responsável | Prazo | Status\n");for(Deployment d:deployments.listOpen())text.append(d.getControlItem().getCode()).append(" | ").append(d.getAction()).append(" | ").append(d.getResponsible()).append(" | ").append(d.getDueDate()).append(" | ").append(d.getStatus()).append("\n");}return text.toString();}
}